### ISSUE TITLE
Cannot install akmod on Fedora 41

### ISSUE THREAD

**Issue by noelmiller** [negativo17/evdi-kmod#2]
Hi There! 

We are trying to build the evdi akmod by installing the `kmod-evdi` package and the `akmod-evdi` packages and we are receiving the following error: 

```
Problem 1: conflicting requests
  - nothing provides evdi-kmod-common >= 1.14.7 needed by akmod-evdi-1.14.7-1.fc41.x86_64 from fedora-multimedia
 Problem 2: package kmod-evdi-1.14.7-1.fc41.x86_64 from fedora-multimedia requires akmod-evdi = 1.14.7-1.fc41, but none of the providers can be installed
  - conflicting requests
  - nothing provides evdi-kmod-common >= 1.14.7 needed by akmod-evdi-1.14.7-1.fc41.x86_64 from fedora-multimedia
```

We do not have issues for this in Fedora 40. Is there something we are missing here? 

Here is our script for building it: https://github.com/ublue-os/akmods/blob/enable-xpadneo-evidi-f41/build-kmod-evdi.sh

Here is the full build failure log: https://github.com/ublue-os/akmods/actions/runs/11587026019/job/32258558584

Thanks, 

Noel Miller

**Comment by scaronni** [comment]
Hi, yes, I simply forgot to build `displaylink` which provides `evdi-kmod-common` for Fedora 41.. I don't have a Displaylink docking station anymore so I'm not using these packages regularly. New version 6.1.0 will be online shortly.

Thanks for reporting!

**Comment by reddy75** [comment]
Hello,

I have similar issue with **akmod-evdi** on **Fedora 40** (kernel 6.12.7-100.fc40.x86_64)

`Building and installing evdi-kmod                          [FAILED]`

[1.14.8-1-for-6.12.7-100.fc40.x86_64.failed.log](https://github.com/user-attachments/files/18310910/1.14.8-1-for-6.12.7-100.fc40.x86_64.failed.log)

Any suggestion?
